# gemini_api.py
import os
import json
from datetime import datetime
import google.generativeai as genai
from pathlib import Path
from config import ARTICLES_DIR, YTDLP_DIR
from gemini_prompt import build_gemini_prompt

def list_gemini_models():
    """List available Gemini models for debugging."""
    try:
        models = genai.list_models()
        return [m.name for m in models if "generateContent" in m.supported_generation_methods]
    except Exception as e:
        print(f"[ERROR] Failed to list Gemini models: {e}")
        return []

def generate_article_with_gemini(task_id: str, transcript: str, input_file: str, emit_fn):
    try:
        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key:
            raise ValueError("GEMINI_API_KEY not found in .env")
        genai.configure(api_key=api_key)

        # Load YouTube metadata if available
        metadata_path = YTDLP_DIR / task_id / "metadata.json"
        metadata = {}
        if metadata_path.exists():
            with open(metadata_path, "r", encoding="utf-8") as f:
                metadata = json.load(f)

        prompt = build_gemini_prompt(transcript, metadata)
        model_name = "gemini-2.5-flash"
        emit_fn(task_id, "article", f"Calling Gemini API ({model_name})...", 96)
        model = genai.GenerativeModel(model_name)
        response = model.generate_content(prompt)

        if not response.text:
            raise ValueError("Empty response from Gemini API")

        # Get truncated title (first 20 chars of metadata title or input file stem)
        base_title = (metadata.get("title") or Path(input_file).stem)[:20]
        # Sanitize for filesystem
        safe_title = "".join(c for c in base_title if c.isalnum() or c in "-_ ").strip()

        article_title = safe_title
        article_content = (
            f"# {article_title}\n\n"
            f"{response.text}\n\n"
            f"*Generated by Gemini API on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*"
        )

        # Save article using the truncated, sanitized filename
        article_filename = f"{safe_title}_{task_id}.md"
        article_path = ARTICLES_DIR / article_filename
        article_path.write_text(article_content, encoding="utf-8")

        return str(article_path), article_content

    except Exception as e:
        emit_fn(task_id, "error", f"Article generation failed: {e}", 95)
        # fallback
        fallback_title = f"Transcript_{Path(input_file).stem[:20]}"
        article_content = f"# {fallback_title}\n\n{transcript}\n\n*Generated automatically from transcript.*"
        article_path = ARTICLES_DIR / f"{fallback_title}_{task_id}.md"
        article_path.write_text(article_content, encoding="utf-8")
        return str(article_path), article_content

